### PR TITLE
Fixing the E2E test

### PR DESCRIPTION
**Pull request by VaijanathB**

### CODE REVIEW

**Comment by dtzar** [comment]
@VaijanathB I fixed the SSH + Travis stuff and linting.  Now it is failing with something specific to the e2e tests themselves.  Specifically this error via the [Travis build](https://travis-ci.org/Azure/terraform-azurerm-computegroup/jobs/336287133).

```
       * azurerm_virtual_machine_scale_set.vm-linux: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LinkedInvalidPropertyId" Message="Property id '' at path 'properties.virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].properties.ipConfigurations[0].properties.subnet.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."
```

**Review by dtzar — CHANGES_REQUESTED** [review]
Fix the one remaining e2e error per the previous comment and then we should be good to merge.

**Comment by metacpp** [comment]
https://github.com/Azure/terraform-azurerm-compute/pull/52

**Comment by metacpp** [comment]
The E2E tests have been migrated to Terratest.

**Pull request closed without merging**
